//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitImageMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitImageMaker.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Apply Ratio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplyRatio {
            get {
                return ResourceManager.GetString("ApplyRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag mouse to select area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DragInstruction {
            get {
                return ResourceManager.GetString("DragInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DragMode {
            get {
                return ResourceManager.GetString("DragMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equal Grid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EqualGrid {
            get {
                return ResourceManager.GetString("EqualGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Output:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FinalOutput {
            get {
                return ResourceManager.GetString("FinalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height Ratio:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HeightRatio {
            get {
                return ResourceManager.GetString("HeightRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse: (0, 0)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MousePosition {
            get {
                return ResourceManager.GetString("MousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split Panel List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PanelList {
            get {
                return ResourceManager.GetString("PanelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste (Ctrl+V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PasteImage {
            get {
                return ResourceManager.GetString("PasteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste to Panel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PasteToPanel {
            get {
                return ResourceManager.GetString("PasteToPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Preview &amp; Area Selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreviewTitle {
            get {
                return ResourceManager.GetString("PreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Combined Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveCombined {
            get {
                return ResourceManager.GetString("SaveCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Images과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveImages {
            get {
                return ResourceManager.GetString("SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Grid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetGrid {
            get {
                return ResourceManager.GetString("SetGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SplitAll {
            get {
                return ResourceManager.GetString("SplitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split Count:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SplitCount {
            get {
                return ResourceManager.GetString("SplitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split Selected Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SplitSelectedArea {
            get {
                return ResourceManager.GetString("SplitSelectedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split Image Maker Pro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width Ratio:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WidthRatio {
            get {
                return ResourceManager.GetString("WidthRatio", resourceCulture);
            }
        }
    }
}
